---
title: "Assignment4"
author: "Junpei Xiao"
date: "2018-2-20"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=F, message=F}
library("tidyverse")
```

### Exercise 12.6.1 Problem 3 and Problem 4

### 3.I claimed that iso2 and iso3 were redundant with country. Confirm this claim.

```{r}

### Check unique values in country,iso2,iso3
who %>% select(1:3) %>% sapply(function(x){length(unique(x))})

### check the unique combination of these three columns
who %>% select(1:3) %>%
  unite(combined, 1:3) %>%
  select(combined) %>%
  distinct() %>%
  nrow()

```

### 4.For each country, year, and sex compute the total number of cases of TB. Make an informative visualisation of the data

```{r}
who %>%
  gather(code, value, new_sp_m014:newrel_f65, na.rm = TRUE) %>% 
  mutate(code = stringr::str_replace(code, "newrel", "new_rel")) %>%
  separate(code, c("new", "var", "sexage")) %>% 
  select(-new, -iso2, -iso3) %>% 
  separate(sexage, c("sex", "age"), sep = 1) %>%
  group_by(country, year, sex) %>%
  summarize(total_case = sum(value)) %>%
  unite(country_sex, country, sex, remove = FALSE) %>%
  ggplot() +
  geom_line(mapping = aes(x = year, y = total_case, color = sex,
                          group = country_sex))

```


### 10.5 Exercise problem 5

### 5 What does tibble::enframe() do? When might you use it?

```{r}
sample <- letters[1:10]
enframe(sample)


### convert vectors to data frames, and vice versa.

```

