---
title: "Table_Convert"
author: "Junpei Xiao"
date: "2018/02/28"
output:
  
  word_document: default
  pdf_document: 
    latex_engine: xelatex
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(printr)
library(tidyr)
library(foreign)
library(tidyverse)
library(dplyr)
```

## Table 4 to table 6 convert

```{r Echo = FALSE,include=TRUE,results='asis'}
# Data from http://pewforum.org/Datasets/Dataset-Download.aspx

# Load data

### Convert Table4 to Table6... The code for creating table 4 is from Author Hadley Wickham.

pew <- read.spss("pew.sav")
pew <- as.data.frame(pew)


religion <- pew[c("q16", "reltrad", "income")]
religion$reltrad <- as.character(religion$reltrad)
religion$reltrad <- str_replace(religion$reltrad, " Churches", "")
religion$reltrad <- str_replace(religion$reltrad, " Protestant", " Prot")
religion$reltrad[religion$q16 == " Atheist (do not believe in God) "] <- "Atheist"
religion$reltrad[religion$q16 == " Agnostic (not sure if there is a God) "] <- "Agnostic"
religion$reltrad <- str_trim(religion$reltrad)
religion$reltrad <- str_replace_all(religion$reltrad, " \\(.*?\\)", "")

religion$income <- c("Less than $10,000" = "<$10k", 
                     "10 to under $20,000" = "$10-20k", 
                     "20 to under $30,000" = "$20-30k", 
                     "30 to under $40,000" = "$30-40k", 
                     "40 to under $50,000" = "$40-50k", 
                     "50 to under $75,000" = "$50-75k",
                     "75 to under $100,000" = "$75-100k", 
                     "100 to under $150,000" = "$100-150k", 
                     "$150,000 or more" = ">150k", 
                     "Don't know/Refused (VOL)" = "Don't know/refused")[religion$income]

religion$income <- factor(religion$income, levels = c("<$10k", "$10-20k", "$20-30k", "$30-40k", "$40-50k", "$50-75k", 
                                                      "$75-100k", "$100-150k", ">150k", "Don't know/refused"))

clean_Table <- religion %>% group_by(reltrad,income)%>% summarise(count=n())
clean_Table<- as.data.frame(clean_Table)
head(clean_Table,n=10)
```

## Table 7 To Table 8 convert


```{r Echo = FALSE,include=TRUE,results='asis'}
bb <-read_csv("billboard.csv")
bb.1 <- bb%>% gather(key="week", value ="rank", -year, -artist.inverted, -track, -time, -genre, -date.entered, -date.peaked)
bb.2 <- bb.1 %>% select(year, artist=artist.inverted, time, track, date=date.entered, week, rank)
bb.3 <-bb.2 %>% arrange(track)
bb.4 <-bb.3 %>% filter(!is.na(rank))
bb.5 <-bb.4 %>% separate(week, into=c("A", "week", "C"), sep=c(1, -7), convert=TRUE)
bb.6 <-bb.5 %>% select(-A, -C)
bb.7 <-bb.6%>% filter(!is.na(week))
#must to specified rename in the dplyr
bb.8 <- bb.7 %>% arrange(artist, track)
bb.9 <-bb.8 %>% mutate(date = date+(week-1)*7)
bb.10 <- bb.9 %>% mutate(rank = as.numeric(bb.9$rank))
head(bb.10,n=10)
```


